apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: worker-deployment
  labels:
    app: worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      restartPolicy: Always
      containers:
        - name: worker
          image: epitechcontent/t-dop-600-worker:k8s
          resources:
            limits:
              memory: "256M"
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: redis-configmap
            - configMapRef:
                name: postgres-configmap
            - secretRef:
                name: postgres-secret
          env:
            - name: REDIS_HOST
              value: redis-service
            - name: POSTGRES_HOST
              value: postgres-service
